import type {
  AdminMessageReport,
  BadgeCounts,
  ChatMessage,
  ConversationDetail,
  ConversationListItem,
  MessagePage,
} from '@ustago/types';
import { z } from 'zod';

/** Faz 7 request/job-bound messaging (docs/adr/0030). */

export const MAX_MESSAGE_LENGTH = 2000;
export const messageTypeSchema = z.enum(['TEXT', 'IMAGE', 'SYSTEM']);
export const conversationRoleSchema = z.enum(['CUSTOMER', 'PROVIDER']);
export const messageReportReasonSchema = z.enum([
  'SPAM',
  'HARASSMENT',
  'FRAUD',
  'CONTACT_INFO',
  'INAPPROPRIATE',
  'OTHER',
]);
export const messageReportStatusSchema = z.enum(['OPEN', 'REVIEWED', 'DISMISSED']);

/**
 * POST /conversations: open (or get) the conversation for a quote or a job.
 * Only the two parties of that quote/job may do it.
 */
export const openConversationSchema = z
  .object({ quoteId: z.uuid().optional(), jobId: z.uuid().optional() })
  .strict()
  .refine((v) => (v.quoteId ? 1 : 0) + (v.jobId ? 1 : 0) === 1, {
    message: 'quoteId veya jobId gönderin (yalnız biri).',
  });
export type OpenConversation = z.infer<typeof openConversationSchema>;

/** Plain text: HTML is never rendered, but tags and control characters are refused. */
const messageBody = z
  .string()
  .trim()
  .min(1, 'Boş mesaj gönderilemez.')
  .max(MAX_MESSAGE_LENGTH, `Mesaj en fazla ${MAX_MESSAGE_LENGTH} karakter olabilir.`)
  // eslint-disable-next-line no-control-regex
  .refine((v) => !/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/.test(v), 'Geçersiz karakter.');

/**
 * POST /conversations/:id/messages. `clientMessageId` is generated by the
 * app once per message: a retry with the same id returns the stored
 * message instead of a duplicate.
 */
export const sendMessageSchema = z.discriminatedUnion('type', [
  z.object({ type: z.literal('TEXT'), clientMessageId: z.uuid(), body: messageBody }).strict(),
  z.object({ type: z.literal('IMAGE'), clientMessageId: z.uuid(), uploadId: z.uuid() }).strict(),
]);
export type SendMessage = z.infer<typeof sendMessageSchema>;

export const listMessagesQuerySchema = z.object({
  /** Older page: messages before this message id. */
  before: z.uuid().optional(),
  /** Polling: only messages after this message id. */
  after: z.uuid().optional(),
  limit: z.coerce.number().int().min(1).max(100).default(30),
});
export type ListMessagesQuery = z.infer<typeof listMessagesQuerySchema>;

export const listConversationsQuerySchema = z.object({
  limit: z.coerce.number().int().min(1).max(50).default(20),
  /** ISO timestamp of the last item's updatedAt, with its id (keyset). */
  cursor: z.string().max(100).optional(),
});
export type ListConversationsQuery = z.infer<typeof listConversationsQuerySchema>;

export const markConversationReadSchema = z.object({ messageId: z.uuid() }).strict();
export type MarkConversationRead = z.infer<typeof markConversationReadSchema>;

export const reportMessageSchema = z
  .object({
    reason: messageReportReasonSchema,
    note: z.string().trim().min(1).max(500).optional(),
  })
  .strict();
export type ReportMessage = z.infer<typeof reportMessageSchema>;

/** Support opening a reported conversation must state why (audited). */
export const accessReportedConversationSchema = z
  .object({ reason: z.string().trim().min(10, 'Gerekçe en az 10 karakter olmalı.').max(500) })
  .strict();
export type AccessReportedConversation = z.infer<typeof accessReportedConversationSchema>;

export const resolveMessageReportSchema = z
  .object({
    status: z.enum(['REVIEWED', 'DISMISSED']),
    note: z.string().trim().min(3).max(500),
  })
  .strict();
export type ResolveMessageReport = z.infer<typeof resolveMessageReportSchema>;

export const listMessageReportsQuerySchema = z.object({
  status: messageReportStatusSchema.optional(),
  limit: z.coerce.number().int().min(1).max(100).default(50),
  cursor: z.uuid().optional(),
});
export type ListMessageReportsQuery = z.infer<typeof listMessageReportsQuerySchema>;

// ---------------------------------------------------------------------------
// Responses
// ---------------------------------------------------------------------------

const categoryRef = z.object({
  id: z.uuid(),
  slug: z.string(),
  name: z.string(),
  icon: z.string().nullable(),
});

export const chatMessageSchema = z.object({
  id: z.uuid(),
  conversationId: z.uuid(),
  type: messageTypeSchema,
  senderRole: conversationRoleSchema.nullable(),
  mine: z.boolean(),
  body: z.string().nullable(),
  hasImage: z.boolean(),
  clientMessageId: z.uuid().nullable(),
  containsContactInfo: z.boolean(),
  state: z.enum(['SENT', 'READ']),
  createdAt: z.iso.datetime(),
  deletedAt: z.iso.datetime().nullable(),
}) satisfies z.ZodType<ChatMessage>;

export const conversationListItemSchema = z.object({
  id: z.uuid(),
  serviceRequestId: z.uuid(),
  jobId: z.uuid().nullable(),
  title: z.string(),
  category: categoryRef,
  counterpart: z.object({
    role: conversationRoleSchema,
    name: z.string(),
    providerId: z.uuid().nullable(),
  }),
  lastMessage: z
    .object({
      type: messageTypeSchema,
      preview: z.string(),
      createdAt: z.iso.datetime(),
      mine: z.boolean(),
    })
    .nullable(),
  unreadCount: z.number().int().min(0),
  updatedAt: z.iso.datetime(),
}) satisfies z.ZodType<ConversationListItem>;

export const conversationDetailSchema = conversationListItemSchema.extend({
  myRole: conversationRoleSchema,
  canSend: z.boolean(),
  cannotSendReason: z.enum(['BLOCKED', 'CLOSED']).nullable(),
  blockedByMe: z.boolean(),
  counterpartLastReadAt: z.iso.datetime().nullable(),
}) satisfies z.ZodType<ConversationDetail>;

export const messagePageSchema = z.object({
  items: z.array(chatMessageSchema),
  hasMoreBefore: z.boolean(),
}) satisfies z.ZodType<MessagePage>;

export const adminMessageReportSchema = z.object({
  id: z.uuid(),
  messageId: z.uuid(),
  conversationId: z.uuid(),
  reason: messageReportReasonSchema,
  note: z.string().nullable(),
  status: messageReportStatusSchema,
  reporterRole: conversationRoleSchema,
  createdAt: z.iso.datetime(),
  reviewedAt: z.iso.datetime().nullable(),
}) satisfies z.ZodType<AdminMessageReport>;

export const badgeCountsSchema = z.object({
  notifications: z.number().int().min(0),
  messages: z.number().int().min(0),
}) satisfies z.ZodType<BadgeCounts>;

/** Phone numbers (TR and international) and e-mail addresses, for detection only. */
const PHONE_PATTERN = /(?:\+?\d[\s().-]?){10,}/;
const EMAIL_PATTERN = /[^\s@]+@[^\s@]+\.[a-z]{2,}/i;
export function looksLikeContactInfo(text: string): boolean {
  return PHONE_PATTERN.test(text) || EMAIL_PATTERN.test(text);
}
