packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@prisma/engines'
  - esbuild
  - prisma
  - sharp
  - unrs-resolver

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@swc/core'
