/**
 * Detects a file's real type from its first bytes. The client's declared
 * MIME type is only a hint: a renamed .exe or an SVG labelled image/png is
 * caught here (docs/adr/0011).
 */
const SIGNATURES: readonly { mime: string; bytes: readonly number[] }[] = [
  { mime: 'image/jpeg', bytes: [0xff, 0xd8, 0xff] },
  { mime: 'image/png', bytes: [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a] },
  // "%PDF-"
  { mime: 'application/pdf', bytes: [0x25, 0x50, 0x44, 0x46, 0x2d] },
];

export const SIGNATURE_BYTES = 8;

export function detectMimeType(prefix: Uint8Array): string | null {
  for (const signature of SIGNATURES) {
    if (signature.bytes.every((byte, index) => prefix[index] === byte)) return signature.mime;
  }
  return null;
}

/** File extension used in storage keys; derived from the verified type only. */
export function extensionFor(mime: string): string {
  switch (mime) {
    case 'image/jpeg':
      return 'jpg';
    case 'image/png':
      return 'png';
    case 'application/pdf':
      return 'pdf';
    default:
      throw new Error(`Unsupported MIME type ${mime}`);
  }
}

/**
 * Keys are generated by the server: <purpose>/<owner uuid>/<random uuid>.<ext>.
 * Anything else (../, absolute paths, user file names) is rejected.
 */
export const STORAGE_KEY_PATTERN =
  /^[a-z][a-z-]{1,40}\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.(jpg|png|pdf)$/;

export function isValidStorageKey(key: string): boolean {
  return STORAGE_KEY_PATTERN.test(key);
}
