/**
 * Reference data that every environment needs. Safe to re-run: the seed
 * only inserts what is missing and never overrides admin choices such as
 * isActive.
 */

/** All 81 provinces with their official plate codes. */
export const PROVINCES: readonly (readonly [number, string])[] = [
  [1, 'Adana'],
  [2, 'Adıyaman'],
  [3, 'Afyonkarahisar'],
  [4, 'Ağrı'],
  [5, 'Amasya'],
  [6, 'Ankara'],
  [7, 'Antalya'],
  [8, 'Artvin'],
  [9, 'Aydın'],
  [10, 'Balıkesir'],
  [11, 'Bilecik'],
  [12, 'Bingöl'],
  [13, 'Bitlis'],
  [14, 'Bolu'],
  [15, 'Burdur'],
  [16, 'Bursa'],
  [17, 'Çanakkale'],
  [18, 'Çankırı'],
  [19, 'Çorum'],
  [20, 'Denizli'],
  [21, 'Diyarbakır'],
  [22, 'Edirne'],
  [23, 'Elazığ'],
  [24, 'Erzincan'],
  [25, 'Erzurum'],
  [26, 'Eskişehir'],
  [27, 'Gaziantep'],
  [28, 'Giresun'],
  [29, 'Gümüşhane'],
  [30, 'Hakkari'],
  [31, 'Hatay'],
  [32, 'Isparta'],
  [33, 'Mersin'],
  [34, 'İstanbul'],
  [35, 'İzmir'],
  [36, 'Kars'],
  [37, 'Kastamonu'],
  [38, 'Kayseri'],
  [39, 'Kırklareli'],
  [40, 'Kırşehir'],
  [41, 'Kocaeli'],
  [42, 'Konya'],
  [43, 'Kütahya'],
  [44, 'Malatya'],
  [45, 'Manisa'],
  [46, 'Kahramanmaraş'],
  [47, 'Mardin'],
  [48, 'Muğla'],
  [49, 'Muş'],
  [50, 'Nevşehir'],
  [51, 'Niğde'],
  [52, 'Ordu'],
  [53, 'Rize'],
  [54, 'Sakarya'],
  [55, 'Samsun'],
  [56, 'Siirt'],
  [57, 'Sinop'],
  [58, 'Sivas'],
  [59, 'Tekirdağ'],
  [60, 'Tokat'],
  [61, 'Trabzon'],
  [62, 'Tunceli'],
  [63, 'Şanlıurfa'],
  [64, 'Uşak'],
  [65, 'Van'],
  [66, 'Yozgat'],
  [67, 'Zonguldak'],
  [68, 'Aksaray'],
  [69, 'Bayburt'],
  [70, 'Karaman'],
  [71, 'Kırıkkale'],
  [72, 'Batman'],
  [73, 'Şırnak'],
  [74, 'Bartın'],
  [75, 'Ardahan'],
  [76, 'Iğdır'],
  [77, 'Yalova'],
  [78, 'Karabük'],
  [79, 'Kilis'],
  [80, 'Osmaniye'],
  [81, 'Düzce'],
];

/**
 * Districts of the three largest provinces, enough for development and a
 * pilot. The remaining provinces' districts are loaded by a data import
 * from an official source before those provinces open (see README).
 */
export const DISTRICTS: Readonly<Record<number, readonly string[]>> = {
  34: [
    'Adalar',
    'Arnavutköy',
    'Ataşehir',
    'Avcılar',
    'Bağcılar',
    'Bahçelievler',
    'Bakırköy',
    'Başakşehir',
    'Bayrampaşa',
    'Beşiktaş',
    'Beykoz',
    'Beylikdüzü',
    'Beyoğlu',
    'Büyükçekmece',
    'Çatalca',
    'Çekmeköy',
    'Esenler',
    'Esenyurt',
    'Eyüpsultan',
    'Fatih',
    'Gaziosmanpaşa',
    'Güngören',
    'Kadıköy',
    'Kağıthane',
    'Kartal',
    'Küçükçekmece',
    'Maltepe',
    'Pendik',
    'Sancaktepe',
    'Sarıyer',
    'Silivri',
    'Sultanbeyli',
    'Sultangazi',
    'Şile',
    'Şişli',
    'Tuzla',
    'Ümraniye',
    'Üsküdar',
    'Zeytinburnu',
  ],
  6: [
    'Akyurt',
    'Altındağ',
    'Ayaş',
    'Bala',
    'Beypazarı',
    'Çamlıdere',
    'Çankaya',
    'Çubuk',
    'Elmadağ',
    'Etimesgut',
    'Evren',
    'Gölbaşı',
    'Güdül',
    'Haymana',
    'Kahramankazan',
    'Kalecik',
    'Keçiören',
    'Kızılcahamam',
    'Mamak',
    'Nallıhan',
    'Polatlı',
    'Pursaklar',
    'Sincan',
    'Şereflikoçhisar',
    'Yenimahalle',
  ],
  35: [
    'Aliağa',
    'Balçova',
    'Bayındır',
    'Bayraklı',
    'Bergama',
    'Beydağ',
    'Bornova',
    'Buca',
    'Çeşme',
    'Çiğli',
    'Dikili',
    'Foça',
    'Gaziemir',
    'Güzelbahçe',
    'Karabağlar',
    'Karaburun',
    'Karşıyaka',
    'Kemalpaşa',
    'Kınık',
    'Kiraz',
    'Konak',
    'Menderes',
    'Menemen',
    'Narlıdere',
    'Ödemiş',
    'Seferihisar',
    'Selçuk',
    'Tire',
    'Torbalı',
    'Urla',
  ],
};

export interface CategorySeed {
  slug: string;
  name: string;
  icon: string;
  supportsNow: boolean;
}

/** Starting categories (PROJECT.md §4). NOW = can be requested as emergency. */
export const CATEGORIES: readonly CategorySeed[] = [
  { slug: 'klima', name: 'Klima', icon: 'air-conditioner', supportsNow: false },
  { slug: 'elektrik', name: 'Elektrik', icon: 'flash', supportsNow: true },
  { slug: 'su-tesisati', name: 'Su Tesisatı', icon: 'water-pipe', supportsNow: true },
  { slug: 'cilingir', name: 'Çilingir', icon: 'key', supportsNow: true },
  { slug: 'beyaz-esya', name: 'Beyaz Eşya', icon: 'washing-machine', supportsNow: false },
  { slug: 'boya-badana', name: 'Boya / Badana', icon: 'paint-roller', supportsNow: false },
  { slug: 'temizlik', name: 'Temizlik', icon: 'broom', supportsNow: false },
  { slug: 'montaj', name: 'Montaj', icon: 'tools', supportsNow: false },
];
