import {
  changeOrderStatusSchema,
  disciplinaryActionStatusSchema,
  disciplinaryActionTypeSchema,
  disputeReasonSchema,
  disputeStatusSchema,
  jobActorSchema,
  jobStatusSchema,
  otpPurposeSchema,
  providerStatusSchema,
  providerTypeSchema,
  quoteRevisionKindSchema,
  quoteStatusSchema,
  reviewStatusSchema,
  roleSchema,
  serviceRequestStatusSchema,
  serviceRequestTypeSchema,
  userStatusSchema,
  verificationStatusSchema,
  verificationTypeSchema,
} from '@ustago/validation';

import {
  ChangeOrderStatus,
  DisciplinaryActionStatus,
  DisciplinaryActionType,
  DisputeReason,
  DisputeStatus,
  JobActor,
  JobStatus,
  OtpPurpose,
  ProviderStatus,
  ProviderType,
  QuoteRevisionKind,
  QuoteStatus,
  ReviewStatus,
  Role,
  ServiceRequestStatus,
  ServiceRequestType,
  UserStatus,
  VerificationStatus,
  VerificationType,
} from '../generated/prisma/client.js';

/** Shared client schemas must stay in sync with the database enums. */
describe('enum parity between Prisma and @ustago/validation', () => {
  it.each([
    ['Role', Role, roleSchema.options],
    ['UserStatus', UserStatus, userStatusSchema.options],
    ['ProviderStatus', ProviderStatus, providerStatusSchema.options],
    ['ProviderType', ProviderType, providerTypeSchema.options],
    ['OtpPurpose', OtpPurpose, otpPurposeSchema.options],
    ['VerificationType', VerificationType, verificationTypeSchema.options],
    ['VerificationStatus', VerificationStatus, verificationStatusSchema.options],
    ['ServiceRequestType', ServiceRequestType, serviceRequestTypeSchema.options],
    ['ServiceRequestStatus', ServiceRequestStatus, serviceRequestStatusSchema.options],
    ['QuoteStatus', QuoteStatus, quoteStatusSchema.options],
    ['QuoteRevisionKind', QuoteRevisionKind, quoteRevisionKindSchema.options],
    ['JobStatus', JobStatus, jobStatusSchema.options],
    ['JobActor', JobActor, jobActorSchema.options],
    ['ChangeOrderStatus', ChangeOrderStatus, changeOrderStatusSchema.options],
    ['DisputeReason', DisputeReason, disputeReasonSchema.options],
    ['DisputeStatus', DisputeStatus, disputeStatusSchema.options],
    ['ReviewStatus', ReviewStatus, reviewStatusSchema.options],
    ['DisciplinaryActionType', DisciplinaryActionType, disciplinaryActionTypeSchema.options],
    ['DisciplinaryActionStatus', DisciplinaryActionStatus, disciplinaryActionStatusSchema.options],
  ])('%s', (_name, prismaEnum, shared) => {
    expect([...shared].sort()).toEqual(Object.values(prismaEnum).sort());
  });
});
