// pnpm dev:setup: one-time local setup.
//   1. checks Node and pnpm
//   2. creates .env from .env.example with random LOCAL-ONLY secrets
//      (an existing .env is never overwritten; only empty secrets are filled)
//   3. installs dependencies if needed and builds the shared packages
//   4. starts PostgreSQL + Redis, applies migrations, loads demo data
// Flags: --skip-docker (only steps 1-3).
import { randomBytes } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import {
  bold,
  ENV_EXAMPLE_PATH,
  ENV_PATH,
  fail,
  migrateAndSeed,
  nodeMajor,
  ok,
  parseEnv,
  ROOT,
  run,
  runOrFail,
  startInfra,
  step,
  warn,
} from './lib.mjs';

const skipDocker = process.argv.includes('--skip-docker');

/** docker-compose.yml names the project "ustago", so its volume is ustago_postgres-data. */
function postgresVolumeExists() {
  return run('docker', ['volume', 'inspect', 'ustago_postgres-data'], { quiet: true }) === 0;
}
const secret = (bytes = 32) => randomBytes(bytes).toString('base64url');

step('Araçlar kontrol ediliyor');
const [major, minor] = process.versions.node.split('.').map(Number);
if (nodeMajor() < 22 || (major === 22 && minor < 12)) {
  fail(
    `Node ${process.versions.node} bulundu; Node 22.12 veya üstü gerekli.`,
    'https://nodejs.org adresinden Node 22 LTS kurun (Windows: .msi yükleyicisi).',
  );
}
ok(`Node ${process.versions.node}`);
if (run('pnpm', ['--version'], { quiet: true }) !== 0) {
  fail('pnpm bulunamadı.', 'Kurmak için: corepack enable  (sonra terminali yeniden açın)');
}
ok('pnpm hazır');

step('.env hazırlanıyor');
/** Keys that get a fresh random value when empty. Never production secrets. */
const GENERATED = {
  JWT_ACCESS_SECRET: () => `local-dev-${secret(36)}`,
  OTP_HASH_SECRET: () => `local-dev-${secret(36)}`,
  STORAGE_SIGNING_SECRET: () => `local-dev-${secret(36)}`,
  SEED_DEV_PASSWORD: () => `Demo-${secret(9)}`,
};
const PLACEHOLDER = /change-me/;

if (!existsSync(ENV_PATH)) {
  let text = readFileSync(ENV_EXAMPLE_PATH, 'utf8');
  // PostgreSQL keeps the password it was first created with. When a UstaGO
  // database volume already exists (an earlier checkout), a new random
  // password would lock us out, so the .env.example value is kept.
  if (postgresVolumeExists()) {
    warn(
      'Mevcut bir UstaGO PostgreSQL verisi bulundu; .env.example’daki veritabanı şifresi kullanılıyor. ' +
        'Farklı bir şifreyle oluşturduysanız .env’deki POSTGRES_PASSWORD ve DATABASE_URL’i ona göre düzeltin.',
    );
  } else {
    const dbPassword = `local${secret(12).replace(/[^A-Za-z0-9]/g, '')}`;
    text = text
      .replace(/^POSTGRES_PASSWORD=.*$/m, `POSTGRES_PASSWORD=${dbPassword}`)
      .replace(
        /^DATABASE_URL=(postgresql:\/\/[^:]+):[^@]*@/m,
        (_, user) => `DATABASE_URL=${user}:${dbPassword}@`,
      );
  }
  for (const [key, make] of Object.entries(GENERATED)) {
    text = text.replace(new RegExp(`^${key}=.*$`, 'm'), `${key}=${make()}`);
  }
  const header =
    '# Generated by `pnpm dev:setup` for LOCAL DEVELOPMENT ONLY. These random values are\n' +
    '# not production secrets; production gets its own from the deployment platform.\n';
  writeFileSync(ENV_PATH, header + text);
  ok('.env oluşturuldu (rastgele yerel sırlar; git tarafından yok sayılır)');
} else {
  let text = readFileSync(ENV_PATH, 'utf8');
  const current = parseEnv(text);
  const filled = [];
  for (const [key, make] of Object.entries(GENERATED)) {
    const value = current[key];
    const empty = value === undefined || value === '';
    // A placeholder JWT secret works locally; only fill genuinely empty keys.
    if (!empty) continue;
    filled.push(key);
    text = new RegExp(`^${key}=.*$`, 'm').test(text)
      ? text.replace(new RegExp(`^${key}=.*$`, 'm'), `${key}=${make()}`)
      : `${text.trimEnd()}\n${key}=${make()}\n`;
  }
  // Expo web (8081) calls the API from the browser, so it needs CORS.
  const cors = current.API_CORS_ORIGINS;
  if (cors && !cors.includes('localhost:8081')) {
    text = text.replace(/^API_CORS_ORIGINS=.*$/m, `API_CORS_ORIGINS=${cors},http://localhost:8081`);
    filled.push('API_CORS_ORIGINS (+ Expo web 8081)');
  }
  if (filled.length > 0) {
    writeFileSync(ENV_PATH, text);
    ok(`.env zaten vardı; eksik değerler tamamlandı: ${filled.join(', ')}`);
  } else {
    ok('.env zaten var, değiştirilmedi');
  }
  if (PLACEHOLDER.test(current.POSTGRES_PASSWORD ?? '')) {
    warn('POSTGRES_PASSWORD örnek değerde; yerel geliştirme için sorun değil.');
  }
}

step('Bağımlılıklar');
if (!existsSync(resolve(ROOT, 'node_modules'))) {
  runOrFail('pnpm', ['install'], 'pnpm install başarısız oldu.');
}
ok('node_modules hazır');
runOrFail(
  'pnpm',
  ['turbo', 'run', 'build', '--filter=./packages/*'],
  'Paylaşılan paketler derlenemedi.',
);
runOrFail('pnpm', ['--filter', '@ustago/api', 'prisma:generate'], 'Prisma client üretilemedi.');
ok('Paylaşılan paketler ve Prisma client hazır');

if (skipDocker) {
  warn('--skip-docker: veritabanı adımları atlandı. Sonra: pnpm dev:infra && pnpm dev:seed');
} else {
  startInfra();
  migrateAndSeed();
}

const env = parseEnv(readFileSync(ENV_PATH, 'utf8'));
console.log(`
${bold('Kurulum tamam.')} Başlatmak için:  ${bold('pnpm dev')}

  API ........ http://localhost:3000/api/v1   (Swagger: http://localhost:3000/api/docs)
  Admin ...... http://localhost:3001          (admin@ustago.test)
  Expo web ... http://localhost:8081

  Demo hesap şifresi (.env > SEED_DEV_PASSWORD): ${env.SEED_DEV_PASSWORD || '(seed çıktısına bakın)'}
  Mobil giriş: +90 500 000 00 01 (müşteri), +90 500 000 00 02 (Demo Klima Ustası)
  OTP kodu SMS ile gitmez; API terminalinde "[DEV SMS → ...] OTP KODU: ......" satırında görünür.
`);
